### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [MarbleGateKeeper/HomingEnderEye#1]
Forge 41.0.94+
homing_ender_eye-1.19-1.3.0

java.lang.NoClassDefFoundError: net/minecraftforge/event/world/WorldEvent$Load

[crashlog](https://github.com/MarbleGateKeeper/HomingEnderEye/files/9127000/crash-2022-07-17_13.37.56-fml.txt)

**Comment by MarbleGateKeeper** [comment]
Fixed in [1a63f55](https://github.com/MarbleGateKeeper/HomingEnderEye/commit/1a63f553db8572f27d0fa940f1bb2a229f53b3b9)

**Comment by Baggytrousers27** [comment]
¦D
